#!/usr/bin/env python3
"""Predeclared near-boundary realizability audit for the 35-moment FP map.

The audit answers the three concrete questions raised after Stage 52:

* what happens as a positive crossing-jet family approaches the H2 boundary;
* which part of the update (diffusion, collision, transport, or splitting)
  first loses a necessary moment-matrix condition; and
* whether the answer is stable under a factor-two time refinement.

H2 and H4 are the normalized moment matrices generated by monomials through
degree one and two, respectively.  H2 uses moments through degree two; H4
uses every retained moment through degree four.  Nonnegative eigenvalues are
necessary for a positive velocity distribution.  They are not a proof of
full realizability.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import subprocess
import sys
import time
from dataclasses import asdict, dataclass, replace
from itertools import product
from math import comb
from pathlib import Path
from typing import Iterable, Sequence

os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("MPLCONFIGDIR", "/tmp/mpl-riemann35-stage53")

import numpy as np

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from hyqmom_fp import (  # noqa: E402
    HYQMOM_35_INDICES,
    finite_gaussian_mixture_fp_step,
    macroscopic_state,
    mixture_of_gaussians_moments_35,
    reconstruct_gaussian_mixture_quadrature,
)
from hyqmom_fp.moments import multivariate_gaussian_raw_moment  # noqa: E402


POSITION = {index: offset for offset, index in enumerate(HYQMOM_35_INDICES)}
H2_BASIS = ((0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1))
H4_BASIS = tuple(
    (i, j, total - i - j)
    for total in range(3)
    for i in range(total + 1)
    for j in range(total - i + 1)
)
METHODS = (
    "diffusion_only",
    "full_fp_collision",
    "transport_only",
    "fp_operator_split",
    "esbgk_collision_baseline",
)
METHOD_LABELS = {
    "diffusion_only": "isotropic diffusion only",
    "full_fp_collision": "proposed HyQMOM-35 FP collision",
    "transport_only": "HyQMOM-35 transport only",
    "fp_operator_split": "proposed HyQMOM-35 FP split",
    "esbgk_collision_baseline": "ES-BGK collision baseline",
}
METHOD_STYLES = {
    "diffusion_only": ("#7f7f7f", "-", "o"),
    "full_fp_collision": ("#000000", "-", "s"),
    "transport_only": ("#377eb8", "--", "^"),
    "fp_operator_split": ("#d95f02", "-.", "D"),
    "esbgk_collision_baseline": ("#cc79a7", ":", "v"),
}


@dataclass(frozen=True)
class Configuration:
    cells: int
    final_time: float
    coarse_dt: float
    fine_dt: float
    sample_interval: float
    tau: float
    prandtl: float
    epsilons: tuple[float, ...]
    weight_amplitude: float
    h_tolerance: float
    conservation_tolerance: float
    refinement_tolerance: float


def configuration(mode: str) -> Configuration:
    """Return the locked smoke or Unity campaign."""

    if mode == "smoke":
        return Configuration(
            cells=8,
            final_time=0.005,
            coarse_dt=0.0025,
            fine_dt=0.00125,
            sample_interval=0.0025,
            tau=1.0,
            prandtl=2.0 / 3.0,
            epsilons=(0.10, 0.03),
            weight_amplitude=0.30,
            h_tolerance=2.0e-10,
            conservation_tolerance=2.0e-10,
            refinement_tolerance=5.0e-2,
        )
    if mode != "unity":
        raise ValueError("mode must be 'smoke' or 'unity'")
    return Configuration(
        cells=48,
        final_time=0.25,
        coarse_dt=0.0025,
        fine_dt=0.00125,
        sample_interval=0.0125,
        tau=1.0,
        prandtl=2.0 / 3.0,
        epsilons=(0.30, 0.10, 0.03, 0.01, 0.003),
        weight_amplitude=0.35,
        h_tolerance=2.0e-10,
        conservation_tolerance=2.0e-9,
        refinement_tolerance=5.0e-2,
    )


def configuration_for_epsilon(mode: str, epsilon_index: int) -> Configuration:
    """Select one locked boundary case without changing any numerical gate."""

    base = configuration(mode)
    if epsilon_index < 0 or epsilon_index >= len(base.epsilons):
        raise ValueError(
            f"epsilon_index must be in [0, {len(base.epsilons) - 1}] for {mode} mode"
        )
    return replace(base, epsilons=(base.epsilons[epsilon_index],))


def crossing_jet_components(
    epsilon: float, weight: float
) -> tuple[tuple[float, np.ndarray, np.ndarray], ...]:
    """Positive two-jet state whose moment matrices approach the boundary."""

    if not 0.0 < epsilon < 1.0:
        raise ValueError("epsilon must lie in (0, 1)")
    if not 0.0 < weight < 1.0:
        raise ValueError("weight must lie in (0, 1)")
    # The non-collinear transverse velocities make this a crossing-jet state,
    # while the common narrow covariance is the declared boundary parameter.
    means = (
        np.asarray((+1.15, +0.75, +0.10)),
        np.asarray((-0.95, -0.60, -0.05)),
    )
    covariance = epsilon * np.asarray(
        ((1.0, 0.15, 0.0), (0.15, 0.80, 0.05), (0.0, 0.05, 0.55))
    )
    return (
        (float(weight), means[0], covariance.copy()),
        (float(1.0 - weight), means[1], covariance.copy()),
    )


def initialize_crossing_jet_field(config: Configuration, epsilon: float) -> np.ndarray:
    """Periodic crossing-jet field with a smooth, positive mixing fraction."""

    centers = (np.arange(config.cells) + 0.5) / config.cells
    weights = 0.5 + config.weight_amplitude * np.sin(2.0 * np.pi * centers)
    return np.asarray(
        [
            mixture_of_gaussians_moments_35(
                crossing_jet_components(epsilon, float(weight))
            )
            for weight in weights
        ]
    )


def normalized_moment_matrix_margin(
    moments: Sequence[float], basis: Sequence[tuple[int, int, int]]
) -> float:
    """Minimum eigenvalue after diagonal equilibration of a moment matrix."""

    vector = np.asarray(moments, dtype=float)
    matrix = np.asarray(
        [
            [
                vector[
                    POSITION[
                        tuple(left[d] + right[d] for d in range(3))
                    ]
                ]
                for right in basis
            ]
            for left in basis
        ]
    )
    matrix = 0.5 * (matrix + matrix.T)
    diagonal = np.diag(matrix)
    if float(np.min(diagonal)) <= 0.0:
        scale = max(float(np.mean(np.abs(diagonal))), np.finfo(float).tiny)
        return float(np.min(np.linalg.eigvalsh(matrix)) / scale)
    inverse_root = diagonal ** -0.5
    equilibrated = inverse_root[:, None] * matrix * inverse_root[None, :]
    return float(np.min(np.linalg.eigvalsh(equilibrated)))


def field_margins(field: np.ndarray) -> tuple[float, float]:
    h2 = min(normalized_moment_matrix_margin(cell, H2_BASIS) for cell in field)
    h4 = min(normalized_moment_matrix_margin(cell, H4_BASIS) for cell in field)
    return float(h2), float(h4)


def _centered_gaussian_moment(index: tuple[int, int, int], variance: float) -> float:
    value = 1.0
    for exponent in index:
        if exponent % 2:
            return 0.0
        for factor in range(1, exponent, 2):
            value *= factor * variance
    return float(value)


def gaussian_diffusion_step(
    moments: Sequence[float], dt: float, diffusivity: float
) -> np.ndarray:
    """Exact positive Gaussian-convolution semigroup through degree four."""

    if dt <= 0.0 or diffusivity <= 0.0:
        raise ValueError("dt and diffusivity must be positive")
    incoming = np.asarray(moments, dtype=float)
    variance = 2.0 * diffusivity * dt
    updated = np.zeros_like(incoming)
    for destination, alpha in enumerate(HYQMOM_35_INDICES):
        value = 0.0
        for bx in range(alpha[0] + 1):
            for by in range(alpha[1] + 1):
                for bz in range(alpha[2] + 1):
                    beta = (bx, by, bz)
                    noise_index = tuple(alpha[d] - beta[d] for d in range(3))
                    coefficient = np.prod(
                        [comb(alpha[d], beta[d]) for d in range(3)]
                    )
                    value += (
                        coefficient
                        * incoming[POSITION[beta]]
                        * _centered_gaussian_moment(noise_index, variance)
                    )
        updated[destination] = value
    return updated


def _gaussian_moments_35(
    rho: float, mean: np.ndarray, covariance: np.ndarray
) -> np.ndarray:
    return np.asarray(
        [
            rho * multivariate_gaussian_raw_moment(index, mean, covariance)
            for index in HYQMOM_35_INDICES
        ]
    )


def esbgk_collision_step(
    moments: Sequence[float], dt: float, tau: float, prandtl: float
) -> np.ndarray:
    """Positivity-preserving frozen-target ES-BGK comparison step."""

    incoming = np.asarray(moments, dtype=float)
    state = macroscopic_state(incoming)
    nu = 1.0 - 1.0 / prandtl
    target_covariance = (
        (1.0 - nu) * state.theta * np.eye(3) + nu * state.covariance
    )
    target_covariance = 0.5 * (target_covariance + target_covariance.T)
    if float(np.min(np.linalg.eigvalsh(target_covariance))) <= 0.0:
        raise FloatingPointError("ES-BGK target covariance is not positive definite")
    target = _gaussian_moments_35(
        state.rho, state.velocity, target_covariance
    )
    tau_stress = 0.5 * tau
    collision_rate = prandtl / tau_stress
    survival = float(np.exp(-collision_rate * dt))
    return survival * incoming + (1.0 - survival) * target


def _point_features(nodes: np.ndarray) -> np.ndarray:
    return np.column_stack(
        [
            nodes[:, 0] ** i * nodes[:, 1] ** j * nodes[:, 2] ** k
            for i, j, k in HYQMOM_35_INDICES
        ]
    )


def periodic_transport_step(field: np.ndarray, dt: float) -> tuple[np.ndarray, float]:
    """Conservative periodic positive-kinetic-flux transport."""

    cells = field.shape[0]
    dx = 1.0 / cells
    positive_flux = np.empty_like(field)
    negative_flux = np.empty_like(field)
    maximum_speed = 0.0
    for cell, moments in enumerate(field):
        quadrature = reconstruct_gaussian_mixture_quadrature(moments)
        features = _point_features(quadrature.nodes)
        velocity_x = quadrature.nodes[:, 0]
        positive = velocity_x >= 0.0
        negative = ~positive
        positive_flux[cell] = features[positive].T @ (
            quadrature.weights[positive] * velocity_x[positive]
        )
        negative_flux[cell] = features[negative].T @ (
            quadrature.weights[negative] * velocity_x[negative]
        )
        maximum_speed = max(maximum_speed, float(np.max(np.abs(velocity_x))))
    cfl = dt * maximum_speed / dx
    if cfl > 0.80 * (1.0 + 1.0e-14):
        raise ValueError(f"periodic transport CFL {cfl:.6g} exceeds 0.8")
    # Face i lies between cell i-1 and i.  Periodicity is exact.
    face_flux = np.roll(positive_flux, 1, axis=0) + negative_flux
    updated = field - dt / dx * (np.roll(face_flux, -1, axis=0) - face_flux)
    if not np.all(np.isfinite(updated)):
        raise FloatingPointError("transport produced NaN or infinity")
    return updated, float(cfl)


def _fp_collision_field(field: np.ndarray, dt: float, config: Configuration) -> np.ndarray:
    updated = np.empty_like(field)
    for cell, moments in enumerate(field):
        updated[cell], _ = finite_gaussian_mixture_fp_step(
            moments,
            dt,
            config.tau,
            prandtl=config.prandtl,
            speed_cap=np.inf,
            quadrature_order=4,
        )
    return updated


def _esbgk_collision_field(
    field: np.ndarray, dt: float, config: Configuration
) -> np.ndarray:
    return np.asarray(
        [
            esbgk_collision_step(cell, dt, config.tau, config.prandtl)
            for cell in field
        ]
    )


def advance_method(
    method: str, field: np.ndarray, dt: float, config: Configuration
) -> tuple[np.ndarray, float]:
    """Advance exactly one declared operator arm."""

    if method == "diffusion_only":
        # Freeze each cell's initial local theta over this substep.  This arm
        # isolates the exact positive Gaussian convolution; energy growth is
        # checked against its analytic value instead of against conservation.
        updated = np.asarray(
            [
                gaussian_diffusion_step(
                    cell, dt, macroscopic_state(cell).theta / config.tau
                )
                for cell in field
            ]
        )
        return updated, 0.0
    if method == "full_fp_collision":
        return _fp_collision_field(field, dt, config), 0.0
    if method == "transport_only":
        return periodic_transport_step(field, dt)
    if method == "fp_operator_split":
        half = _fp_collision_field(field, 0.5 * dt, config)
        transported, cfl = periodic_transport_step(half, dt)
        return _fp_collision_field(transported, 0.5 * dt, config), cfl
    if method == "esbgk_collision_baseline":
        return _esbgk_collision_field(field, dt, config), 0.0
    raise ValueError(f"unknown method: {method}")


def global_invariants(field: np.ndarray) -> np.ndarray:
    total = np.sum(field, axis=0)
    return np.asarray(
        [
            total[POSITION[(0, 0, 0)]],
            total[POSITION[(1, 0, 0)]],
            total[POSITION[(0, 1, 0)]],
            total[POSITION[(0, 0, 1)]],
            sum(
                total[POSITION[index]]
                for index in ((2, 0, 0), (0, 2, 0), (0, 0, 2))
            ),
        ]
    )


def relative_invariant_drift(initial: np.ndarray, current: np.ndarray) -> np.ndarray:
    scale = np.maximum(np.abs(initial), 1.0)
    return np.abs(current - initial) / scale


def quadrature_diagnostics(field: np.ndarray) -> tuple[float, float]:
    minimum_weight = np.inf
    maximum_residual = 0.0
    for cell in field:
        quadrature = reconstruct_gaussian_mixture_quadrature(cell)
        minimum_weight = min(minimum_weight, float(np.min(quadrature.weights)))
        maximum_residual = max(
            maximum_residual, quadrature.relative_moment_residual
        )
    return float(minimum_weight), float(maximum_residual)


def _sample_steps(steps: int, stride: int) -> set[int]:
    requested = set(range(0, steps + 1, stride))
    requested.add(steps)
    return requested


def run_history(
    method: str,
    epsilon: float,
    dt: float,
    config: Configuration,
) -> dict[str, object]:
    """Run one method/case/time-step history with no adaptive gate changes."""

    steps = int(round(config.final_time / dt))
    if not np.isclose(steps * dt, config.final_time):
        raise ValueError("final_time must be an integer number of time steps")
    stride = max(1, int(round(config.sample_interval / dt)))
    requested = _sample_steps(steps, stride)
    field = initialize_crossing_jet_field(config, epsilon)
    initial_invariants = global_invariants(field)
    times: list[float] = []
    h2_history: list[float] = []
    h4_history: list[float] = []
    weight_history: list[float] = []
    residual_history: list[float] = []
    conservation_history: list[float] = []
    cfl_history: list[float] = []
    status = "REACHED_FINAL_TIME"
    message = ""
    maximum_cfl = 0.0

    def record(step: int) -> None:
        h2, h4 = field_margins(field)
        if method == "esbgk_collision_baseline":
            # The ES-BGK step is an explicit convex combination of the
            # incoming positive VDF and a positive Gaussian target.  It has no
            # finite closure quadrature, so a minimum quadrature weight is not
            # a meaningful diagnostic for this baseline.
            minimum_weight, maximum_residual = float("nan"), float("nan")
        else:
            minimum_weight, maximum_residual = quadrature_diagnostics(field)
        invariants = global_invariants(field)
        drift = relative_invariant_drift(initial_invariants, invariants)
        times.append(step * dt)
        h2_history.append(h2)
        h4_history.append(h4)
        weight_history.append(minimum_weight)
        residual_history.append(maximum_residual)
        if method == "diffusion_only":
            conservation_history.append(float(np.max(drift[:4])))
        else:
            conservation_history.append(float(np.max(drift)))
        cfl_history.append(maximum_cfl)

    start = time.perf_counter()
    record(0)
    completed_steps = 0
    for step in range(1, steps + 1):
        try:
            field, cfl = advance_method(method, field, dt, config)
            maximum_cfl = max(maximum_cfl, cfl)
            completed_steps = step
            if step in requested:
                record(step)
        except Exception as error:  # campaign records failures instead of hiding them
            status = "FAILED"
            message = f"{type(error).__name__}: {error}"
            break
    return {
        "method": method,
        "epsilon": epsilon,
        "dt": dt,
        "status": status,
        "message": message,
        "steps": steps,
        "completed_steps": completed_steps,
        "times": np.asarray(times),
        "h2_history": np.asarray(h2_history),
        "h4_history": np.asarray(h4_history),
        "minimum_weight_history": np.asarray(weight_history),
        "maximum_reconstruction_residual_history": np.asarray(residual_history),
        "conservation_history": np.asarray(conservation_history),
        "maximum_cfl_history": np.asarray(cfl_history),
        "final_field": field,
        "elapsed_seconds": time.perf_counter() - start,
    }


def relative_field_difference(left: np.ndarray, right: np.ndarray) -> float:
    scale = max(float(np.linalg.norm(right)), np.finfo(float).tiny)
    return float(np.linalg.norm(left - right) / scale)


def _git_commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=REPOSITORY_ROOT, text=True
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _manifest(
    config: Configuration, mode: str, epsilon_index: int | None
) -> dict[str, object]:
    payload = {
        "stage": 53,
        "mode": mode,
        "epsilon_index": epsilon_index,
        "configuration": asdict(config),
        "methods": list(METHODS),
        "method_labels": METHOD_LABELS,
        "h2_definition": "degree-1 monomial moment matrix; moments through degree 2",
        "h4_definition": "degree-2 monomial moment matrix; moments through degree 4",
        "h_scope": "nonnegative is necessary, not sufficient; negative is decisive",
        "diffusion_scope": "exact isotropic Gaussian convolution control at the moment level",
        "full_fp_method": "finite Gaussian-mixture HyQMOM-35 cubic-FP map",
        "esbgk_scope": "positivity-preserving frozen-target ES-BGK comparison, matched stress clock",
        "time_refinement": "coarse_dt / fine_dt = 2",
        "prohibited_changes": [
            "no smoothing",
            "no curve fitting",
            "no moment replacement",
            "no gate relaxation",
        ],
        "git_commit": _git_commit(),
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    payload["manifest_sha256"] = hashlib.sha256(canonical.encode()).hexdigest()
    return payload


def _write_history_csv(path: Path, histories: Iterable[dict[str, object]]) -> None:
    fields = (
        "method",
        "epsilon",
        "dt",
        "time",
        "h2_margin",
        "h4_margin",
        "minimum_quadrature_weight",
        "maximum_reconstruction_residual",
        "conservation_error",
        "maximum_cfl",
    )
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        for result in histories:
            for offset, time_value in enumerate(result["times"]):
                writer.writerow(
                    {
                        "method": result["method"],
                        "epsilon": result["epsilon"],
                        "dt": result["dt"],
                        "time": time_value,
                        "h2_margin": result["h2_history"][offset],
                        "h4_margin": result["h4_history"][offset],
                        "minimum_quadrature_weight": (
                            ""
                            if np.isnan(result["minimum_weight_history"][offset])
                            else result["minimum_weight_history"][offset]
                        ),
                        "maximum_reconstruction_residual": (
                            ""
                            if np.isnan(
                                result["maximum_reconstruction_residual_history"][offset]
                            )
                            else result["maximum_reconstruction_residual_history"][offset]
                        ),
                        "conservation_error": result["conservation_history"][offset],
                        "maximum_cfl": result["maximum_cfl_history"][offset],
                    }
                )


def _summary(
    config: Configuration, histories: list[dict[str, object]]
) -> dict[str, object]:
    records = []
    for epsilon in config.epsilons:
        for method in METHODS:
            coarse = next(
                item
                for item in histories
                if item["epsilon"] == epsilon
                and item["method"] == method
                and item["dt"] == config.coarse_dt
            )
            fine = next(
                item
                for item in histories
                if item["epsilon"] == epsilon
                and item["method"] == method
                and item["dt"] == config.fine_dt
            )
            refinement = (
                relative_field_difference(coarse["final_field"], fine["final_field"])
                if coarse["status"] == fine["status"] == "REACHED_FINAL_TIME"
                else float("inf")
            )
            min_h2 = float(min(np.min(coarse["h2_history"]), np.min(fine["h2_history"])))
            min_h4 = float(min(np.min(coarse["h4_history"]), np.min(fine["h4_history"])))
            if method == "esbgk_collision_baseline":
                min_weight = None
            else:
                min_weight = float(
                    min(
                        np.min(coarse["minimum_weight_history"]),
                        np.min(fine["minimum_weight_history"]),
                    )
                )
            conservation = float(
                max(
                    np.max(coarse["conservation_history"]),
                    np.max(fine["conservation_history"]),
                )
            )
            gates = {
                "completed": coarse["status"] == fine["status"] == "REACHED_FINAL_TIME",
                "H2": min_h2 >= -config.h_tolerance,
                "H4": min_h4 >= -config.h_tolerance,
                "positive_quadrature_weight": (
                    True if min_weight is None else min_weight > 0.0
                ),
                "conservation": conservation <= config.conservation_tolerance,
                "time_refinement": refinement <= config.refinement_tolerance,
            }
            records.append(
                {
                    "epsilon": epsilon,
                    "method": method,
                    "method_label": METHOD_LABELS[method],
                    "minimum_H2_margin": min_h2,
                    "minimum_H4_margin": min_h4,
                    "minimum_quadrature_weight": min_weight,
                    "maximum_conservation_error": conservation,
                    "coarse_fine_relative_field_L2": refinement,
                    "gates": gates,
                    "status": "PASS" if all(gates.values()) else "HOLD",
                    "coarse_message": coarse["message"],
                    "fine_message": fine["message"],
                }
            )
    boundary_initial_h2 = []
    boundary_initial_h4 = []
    for epsilon in config.epsilons:
        h2, h4 = field_margins(initialize_crossing_jet_field(config, epsilon))
        boundary_initial_h2.append(h2)
        boundary_initial_h4.append(h4)
    monotone_h2 = (
        None
        if len(boundary_initial_h2) < 2
        else bool(
            all(
                boundary_initial_h2[offset + 1] < boundary_initial_h2[offset]
                for offset in range(len(boundary_initial_h2) - 1)
            )
        )
    )
    return {
        "stage": 53,
        "overall_status": "PASS" if all(item["status"] == "PASS" for item in records) else "HOLD",
        "boundary_family": {
            "epsilon": list(config.epsilons),
            "initial_H2_margin": boundary_initial_h2,
            "initial_H4_margin": boundary_initial_h4,
            "H2_strictly_approaches_zero": monotone_h2,
        },
        "records": records,
        "interpretation": {
            "kinetic_diffusion": "PSD Gaussian diffusion preserves positivity at the VDF level.",
            "discrete_closure": "That kinetic fact does not by itself prove realizability of a finite moment closure or a split discretization.",
            "H_theorem": "Absence of a proved H-theorem is not equivalent to nonrealizability; the properties require separate tests.",
        },
    }


def _write_figures(
    output: Path, config: Configuration, histories: list[dict[str, object]]
) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    for epsilon in config.epsilons:
        fig, axes = plt.subplots(2, 2, figsize=(12.0, 8.0))
        fine_histories = [
            item
            for item in histories
            if item["epsilon"] == epsilon and item["dt"] == config.fine_dt
        ]
        for item in fine_histories:
            color, linestyle, marker = METHOD_STYLES[item["method"]]
            label = METHOD_LABELS[item["method"]]
            style = dict(
                color=color,
                ls=linestyle,
                lw=2,
                marker=marker,
                ms=4,
                markevery=max(1, len(item["times"]) // 8),
                label=label,
            )
            axes[0, 0].plot(item["times"], item["h2_history"], **style)
            axes[0, 1].plot(item["times"], item["h4_history"], **style)
            axes[1, 0].plot(item["times"], item["minimum_weight_history"], **style)
            axes[1, 1].plot(
                item["times"],
                np.maximum(item["conservation_history"], 1.0e-18),
                **style,
            )
        axes[0, 0].set_ylabel("minimum normalized H2 eigenvalue")
        axes[0, 1].set_ylabel("minimum normalized H4 eigenvalue")
        axes[1, 0].set_ylabel("minimum quadrature weight")
        axes[1, 1].set_ylabel("relative conservation error")
        for axis in axes.ravel():
            axis.set_xlabel(r"Time, $t/\tau$")
            axis.grid(alpha=0.25)
        axes[1, 0].set_yscale("log")
        axes[1, 1].set_yscale("log")
        axes[1, 0].text(
            0.02,
            0.06,
            "ES-BGK continuous positive target:\nfinite quadrature weight is n/a.",
            transform=axes[1, 0].transAxes,
            fontsize=8,
            bbox={"facecolor": "white", "alpha": 0.85, "edgecolor": "none"},
        )
        handles, labels = axes[0, 0].get_legend_handles_labels()
        fig.suptitle(
            f"Stage 53 crossing jets near the boundary: epsilon={epsilon:g}",
            y=0.985,
        )
        fig.legend(
            handles,
            labels,
            loc="upper center",
            bbox_to_anchor=(0.5, 0.945),
            ncol=3,
            frameon=False,
        )
        fig.tight_layout(rect=(0.0, 0.0, 1.0, 0.84))
        fig.savefig(output / f"stage53_epsilon_{epsilon:g}.png", dpi=220, bbox_inches="tight")
        fig.savefig(output / f"stage53_epsilon_{epsilon:g}.pdf", bbox_inches="tight")
        plt.close(fig)

    fig, axes = plt.subplots(1, 3, figsize=(14.0, 4.2))
    for method in METHODS:
        color, linestyle, marker = METHOD_STYLES[method]
        records = []
        for epsilon in config.epsilons:
            item = next(
                value
                for value in histories
                if value["epsilon"] == epsilon
                and value["method"] == method
                and value["dt"] == config.fine_dt
            )
            records.append(item)
        axes[0].plot(config.epsilons, [np.min(item["h2_history"]) for item in records], marker=marker, color=color, ls=linestyle, label=METHOD_LABELS[method])
        axes[1].plot(config.epsilons, [np.min(item["h4_history"]) for item in records], marker=marker, color=color, ls=linestyle, label=METHOD_LABELS[method])
        axes[2].plot(config.epsilons, [max(np.max(item["conservation_history"]), 1.0e-18) for item in records], marker=marker, color=color, ls=linestyle, label=METHOD_LABELS[method])
    axes[0].set_ylabel("minimum H2 margin")
    axes[1].set_ylabel("minimum H4 margin")
    axes[2].set_ylabel("maximum conservation error")
    for axis in axes:
        axis.set_xscale("log")
        axis.invert_xaxis()
        axis.set_xlabel(r"boundary parameter $\epsilon \to 0^+$")
        axis.grid(alpha=0.25)
    axes[2].set_yscale("log")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        loc="upper center",
        bbox_to_anchor=(0.5, 0.98),
        ncol=3,
        frameon=False,
    )
    fig.tight_layout(rect=(0.0, 0.0, 1.0, 0.84))
    fig.savefig(output / "stage53_boundary_overview.png", dpi=220, bbox_inches="tight")
    fig.savefig(output / "stage53_boundary_overview.pdf", bbox_inches="tight")
    plt.close(fig)


def _write_report(output: Path, summary: dict[str, object], manifest: dict[str, object]) -> None:
    records = summary["records"]
    lines = [
        "# Stage 53: near-boundary realizability qualification",
        "",
        f"Overall predeclared status: **{summary['overall_status']}**.",
        "",
        "H2 is the degree-1 monomial moment matrix (moments through degree 2). H4 is the degree-2 monomial moment matrix (moments through degree 4). Their PSD conditions are necessary, not sufficient.",
        "",
        "| epsilon | arm | min H2 | min H4 | min weight | conservation | dt refinement | status |",
        "|---:|---|---:|---:|---:|---:|---:|:---:|",
    ]
    for record in records:
        weight_text = (
            "n/a (continuous positive baseline)"
            if record["minimum_quadrature_weight"] is None
            else f"{record['minimum_quadrature_weight']:.3e}"
        )
        lines.append(
            f"| {record['epsilon']:.3g} | {record['method_label']} | "
            f"{record['minimum_H2_margin']:.3e} | "
            f"{record['minimum_H4_margin']:.3e} | {weight_text} | "
            f"{record['maximum_conservation_error']:.3e} | "
            f"{record['coarse_fine_relative_field_L2']:.3e} | "
            f"{record['status']} |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- Positive-semidefinite Gaussian diffusion preserves positivity of the velocity distribution under the exact kinetic semigroup.",
            "- This does not automatically prove realizability of the reconstructed 35-moment state after closure, transport, or operator splitting; those are audited separately above.",
            "- A missing H-theorem is not evidence of nonrealizability. Entropy monotonicity and moment-cone invariance are distinct mathematical properties.",
            "",
            "## Reproducibility",
            "",
            f"- Commit: `{manifest['git_commit']}`",
            f"- Manifest SHA-256: `{manifest['manifest_sha256']}`",
            "- No smoothing, curve fitting, moment replacement, or gate relaxation is used.",
        ]
    )
    (output / "STAGE53_RESULTS.md").write_text("\n".join(lines) + "\n")


def run_campaign(
    mode: str, output: Path, epsilon_index: int | None = None
) -> dict[str, object]:
    config = (
        configuration(mode)
        if epsilon_index is None
        else configuration_for_epsilon(mode, epsilon_index)
    )
    output.mkdir(parents=True, exist_ok=True)
    manifest = _manifest(config, mode, epsilon_index)
    (output / "stage53_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    histories: list[dict[str, object]] = []
    for epsilon, method, dt in product(
        config.epsilons, METHODS, (config.coarse_dt, config.fine_dt)
    ):
        print(
            f"[stage53] epsilon={epsilon:g} method={method} dt={dt:g}",
            flush=True,
        )
        histories.append(run_history(method, epsilon, dt, config))
    summary = _summary(config, histories)
    _write_history_csv(output / "stage53_histories.csv", histories)
    serializable_summary = json.loads(
        json.dumps(summary, allow_nan=True)
    )
    (output / "stage53_summary.json").write_text(
        json.dumps(serializable_summary, indent=2, sort_keys=True) + "\n"
    )
    _write_figures(output, config, histories)
    _write_report(output, summary, manifest)
    print(
        f"[stage53] completed status={summary['overall_status']} output={output}",
        flush=True,
    )
    return summary


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=("smoke", "unity"), default="smoke")
    parser.add_argument(
        "--output",
        type=Path,
        default=REPOSITORY_ROOT / "results" / "riemann35_stage53",
    )
    parser.add_argument(
        "--epsilon-index",
        type=int,
        default=None,
        help="run only the indexed locked epsilon case (Unity array tasks use 0..4)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    run_campaign(args.mode, args.output, args.epsilon_index)


if __name__ == "__main__":
    main()
